Feature/take snap
beaconFUN/supsnap-app pull request #32
Opened 2017-10-18 09:01 UTC by Ozakimasanobu

サーバから写真を取得
idを自動生成

2017-10-19 00:12 UTC, uehara1414 requested changes

2017-10-19 00:12 UTC, uehara1414 commented on app/src/main/java/net/beaconfun/myapplication/HistoryAdapter.java
> +            viewHolder.thumImage.setImageBitmap(bitmap); // FIXME: 2017/10/09 実際にDBに保存されているデータに変更する
ここのコメントは外す

2017-10-19 00:12 UTC, uehara1414 commented on app/src/main/java/net/beaconfun/myapplication/SupSnapActivity.java
> +                            //MockData();
いらないので消去してくれ

2017-10-19 00:12 UTC, uehara1414 commented on app/src/main/java/net/beaconfun/myapplication/SupSnapActivity.java
> +                            // FIXME: 2017/10/11 撮影機能を実装
このコメントも、実装できたので消去して

2017-10-19 00:12 UTC, uehara1414 commented on app/src/main/java/net/beaconfun/myapplication/AsyncNetwork.java
> +          Bitmap bit = BitmapFactory.decodeByteArray(bytes, 0, bytes.length);
インデントを揃えてください

2017-10-19 00:12 UTC, uehara1414 commented on app/src/main/java/net/beaconfun/myapplication/AsyncNetwork.java
> +import android.graphics.Bitmap;
使われていないパッケージを消去してください

2017-10-19 00:12 UTC, uehara1414 commented on app/src/main/java/net/beaconfun/myapplication/HistoryActivity.java
> +    private AsyncNetwork task = new AsyncNetwork();
使ってないので削除。
このファイルについては、一切の変更が要らないので全部戻しちゃってください。

2017-10-20 01:49 UTC, Ozakimasanobu commented
修正しました

2017-10-20 02:17 UTC, uehara1414 commented
LGTM!

2017-10-20 02:17 UTC, uehara1414 approved these changes

2017-10-20 02:17 UTC, merged